name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: M-a-z-e-n
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#0A3D62&color_dots=#EBEDF0,#9BE9A8,#40C463,#216E39,#144620
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00C2FF&color_dots=#161B22,#0A3D62,#0A6EBD,#00C2FF,#00C2FF

      - name: Remove progress bar from SVG
        run: |
          sed -i 's/<rect class="u u0"[^>]*\/>//g' dist/github-contribution-grid-snake.svg
          sed -i 's/<rect class="u u0"[^>]*\/>//g' dist/github-contribution-grid-snake-dark.svg

      - name: Push output to `output` branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
